data_dir: /workspace/tensorflow_datasets
type: tensorflow_dataset
train:
  name: imagenet2012:5.1.0
  split: "train"  # 49k
  drop_remainder: True

  repeat: True
  shuffle: True
  batch_size: 4096
  
  preprocess: ???
  postprocess: ???
  
test:
  name: imagenet2012:5.1.0
  split: "validation"
  drop_remainder: False

  batch_size: 4096

  preprocess: ???
  postprocess: ???
  